% This code plots the figure 5 in Wang et al. CEE manuscript
% This code was originally run using MATLAB R2023b on December 3rd, 2024

clear;clc;

% Please make sure that you have fig5_mantle.mat and fig5_melt.mat in the
% work folder; if not, please run Make_primary.m first

% CI chondrite values from McDonough & Sun (1995) CG
CI=[0.237,0.613,0.0928,0.457,0.148,0.0563,0.199,0.0361,0.246,0.0546,0.16,0.0247,0.161,0.0246];

load('fig5_mantle.mat'); % Load mantle_comp (generated by running Make_primary.m)
mantle_comp=mantle_comp./CI;

load('fig5_melt.mat'); % Load primary_melt (generated by running Make_primary.m)

Apollo_troct=[1055.45	964.66	865.96	913.98	913.98	22.88	913.98	673.17	414.18	504.81	615.27	685.39	552.32	552.32
4141.78	3459.89	2996.14	2548.3	3278.12	126.35	2128.75	1778.28	1539.93	1625.31	1746.58	1876.88	1980.96	1980.96];
% Apollo troctolite parental magma REE contents. Digitalized from Fig. 7 of Elardo & Astudillo Manosalva (2023) GCA

    % La     Ce      Pr      Nd      Sm      Eu      Gd     Tb      Dy      Ho      Er     Tm      Yb      Lu
KD=[0.00006	0.00004	0.00004	0.00014	0.00020	0.00024	0.00067	0.00106	0.00185	0.00310	0.00490	0.00770	0.01070	0.01680   % Ol
    0.00390	0.00530	0.00711	0.00970	0.01770	0.01695	0.03145	0.04125	0.05230	0.06635	0.08293	0.10319	0.12767	0.15682   % Opx
    0.02750	0.04300	0.06484	0.09650	0.15000	0.15500	0.18500	0.19500	0.21500	0.22227	0.23000	0.23730	0.24500	0.24500   % Cpx
    0.00310	0.00481	0.00771	0.01240	0.02550	0.03690	0.04550	0.06000	0.07250	0.08635	0.10300	0.11793	0.13550	0.15750   % Pgt
    0.00240	0.00190	0.00044	0.00120	0.00170	0.00130	0.00465	0.00820	0.01105	0.01400	0.02450	0.03745	0.05000	0.06500   % Ilm
    0.02617	0.02005	0.01785	0.01574	0.01137	1.32125	0.00726	0.00639	0.00576	0.00519	0.00470	0.00423	0.00382	0.00388   % Pl
    0.00090	0.00030	0.00038	0.00072	0.00105	0.00035	0.00113	0.00030	0.00060	0.00028	0.00062	0.00050	0.00063	0.00057   % Sp
    0.01000	0.02000	0.05000	0.09000	0.22000	0.33000	0.50000	0.78000	1.06000	1.60500	2.15000	3.07500	4.00000	4.00000]; % Grt
% Using coefficients in Fu & Jacobsen (2024) EPSL

% F defines the fraction of residual melt during fractional crystallization
% Thus, fractionation degree = 1-F
F=[0.01,0.02,0.03,0.05,0.1,0.2,0.5];

% Fractionated mineral model abundances (Modal = [ol, opx, cpx, pgt, ilm, pl, sp, grt])
Modal1=[0.4,0,0,0,0,0.6,0,0];  % If fractionation degree <= 0.87, then trotolite formed
Modal2=[0,0.5,0,0,0,0.5,0,0]; % If fractionation degree > 0.87, then norite formed
% The modal abundances of Modal1 and Modal2 were referenced from modal
% ratios of typical KREEP-free troctolite (Gross et al. 2019 JGR-P) and
% norite (this study) respectively.

% CLf stores the trace-element evolution modeling results
CLf=zeros([length(F), 14]);

% Calculate the fractionated mineral modal abundances
for i=1:length(F)
    if F(i)>=0.13   % If fractionation degree <= 0.87
        Modal=Modal1;  
    else            % If fractionation degree > 0.87
        Modal=Modal1.*0.87+Modal2.*(1-F(i)-0.87);
        Modal=Modal./sum(Modal);
    end
    D=Modal*KD;
    % Fractional crystallization calculation
    CLf(i,:)=primary_melt.*F(i).^(D-1);
end

% Import the literature data for plotting and comparison
dat=readmatrix('fig5_data.xlsx');
A002=[dat(48,33:46);dat(49,33:46)]./CI;
N10401=dat(83,33:46)./CI;
N11788=dat(189,33:46)./CI;
N7611=dat(199,33:46)./CI;
N10986=dat(212,33:46)./CI;

% Plot figure 5 in the main text
figure;
x=1:1:14;
hold on

plot(x,CLf(1,:),'Color','k','LineStyle','--')
plot(x,CLf(2,:),'Color','k','LineStyle','--')
plot(x,CLf(3,:),'Color','k','LineStyle','--')
plot(x,CLf(4,:),'Color','k','LineStyle','--')
plot(x,CLf(5,:),'Color','k','LineStyle','--')
plot(x,CLf(6,:),'Color','k','LineStyle','--')
plot(x,CLf(7,:),'Color','k','LineStyle','--')

p1=plot(x,mantle_comp,'LineWidth',2);
p2=plot(x,primary_melt,'LineWidth',2);
p3=plot(x,N10401,'LineWidth',1.25,'Color',[221 81 58]./255);
p4=plot(x,N11788,'LineWidth',1.25,'Color',[147 38 103]./255);
p5=plot(x,N7611,'LineWidth',1.25,'Color',[50 41 173]./255);
p6=plot(x,N10986,'LineWidth',1.25,'Color',[38 89 216]./255);
p7=errorbar(x,A002(1,:),A002(2,:),"-s","MarkerSize",6,'LineWidth',1.25,'Color',[66 10 104]./255,...
    "MarkerEdgeColor",[66 10 104]./255,"MarkerFaceColor",[87 87 249]./255,'CapSize',0);
fill([x,fliplr(x)],[Apollo_troct(1,:),fliplr(Apollo_troct(2,:))],[0.24,0.51,0.98],'FaceAlpha',0.5,'EdgeColor','none')

hold off

text(0.48, 0.89, 'Apollo Mg-suite parental melts', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 12,'FontName','Calibri');

text(0.94, 0.83, '99', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.77, '98', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.73, '97', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.69, '95', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.625, '90', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.56, '80', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.485, '50', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');
text(0.94, 0.415, '0', 'Units', 'normalized', 'VerticalAlignment',...
    'top', 'FontSize', 11,'FontName','Calibri');

xlim([0.5 15])
ylim([0.1 5000])
lgd=legend([p1,p2,p3,p4,p5,p6,p7],'LPUM (source region)','1% partial melt from LPUM',...
    'Troctolitic clast in NWA 10401', ...
    'Troctolitic clast in NWA 11788','Olivine noritic clast in NWA 7611',...
    'Noritic clast in NWA 10986','Arguin 002',...
    'Position', [0.33, 0.26,.1,.1]);

xticks(x);
xticklabels({'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', ...
    'Ho', 'Er', 'Tm', 'Yb', 'Lu'});
xlabel('Trace elements')
ylabel('Sample / Chondrite')
set(gca, 'Box', 'on', 'YScale', 'log',...                          
         'LineWidth', .75, 'FontName', 'Calibri', 'FontSize', 12,...       
         'XGrid', 'off', 'YGrid', 'off', ...                           
         'FontName', 'Calibri', 'FontSize', 12,...
         'TickDir', 'out', 'TickLength', [.01 .01])
set(lgd, 'FontName',  'Calibri', 'FontSize', 12)

% Output the figure
figureUnits = 'centimeters';
figureHandle = get(groot,'CurrentFigure');
figW = 550;
figH = 550;
set(figureHandle,'PaperUnits',figureUnits);
set(figureHandle,'Position',[80 80 figW figH]);
set(gca, 'LooseInset', get(gca, 'TightInset')); 
set(gcf, 'PaperPositionMode', 'auto');
figureHandle.Renderer='Painters';

fileout = 'fig5';
exportgraphics(gcf,[fileout,'.pdf'], 'ContentType', 'vector');